development:
  adapter: postgresql
  database: hfm_development
  username: nicolasiensen
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hfm_test
  username: nicolasiensen
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: /tmp
  database: hfm_production
  pool: 5
  timeout: 5000
