development:
  adapter: postgresql
  database: hfm_development
  username: postgres
  password: password
  host: db
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hfm_test
  username: postgres
  password: password
  host: db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: /tmp
  database: hfm_production
  pool: 5
  timeout: 5000
